# Assume Python 3.12
target-version = "py312"

# Exclude a variety of commonly ignored directories.
exclude = [ ".git", ".vscode", "log", "temp", "venv", "old", "build", "dist" ]

# Same as Black.
line-length = 180
indent-width = 4

# By default, always show source code snippets.
output-format = "full"
fix = true

[lint]
# For rules: https://beta.ruff.rs/docs/rules
select = [
    "E",
    "F",
    "B",
    "I",
]
ignore = [ "C901", "E701", "E402", "D203", "E211", "I001", "B904", "B008", "B905", "B028", "E741", "E731" ]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = [
  # Don't touch unused imports
  "F401",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
