name: Publish package to PyPI

on:
  release:
    types:
      - created

env:
  HATCH_VERBOSE: 0

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.7.3,<0.9.0"
          enable-cache: true
          cache-dependency-glob: |
            requirements-dev.txt

      - name: Install dependencies
        run: |
          uv pip install --upgrade "pip>=25.1.1,<26.0.0" --system;
          uv pip install "$(cat requirements-dev.txt | grep hatch)" --system;

      - name: Build distribution
        run: hatch build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
